export const BOX_VARIANTS = 'boxVariants'
export const BUTTON_VARIANTS = 'buttonVariants'
export const GRID_VARIANTS = 'gridVariants'
export const IMAGE_VARIANTS = 'imageVariants'
export const INPUT_VARIANTS = 'inputVariants'
export const LABEL_VARIANTS = 'labelVariants'
export const LINK_VARIANTS = 'linkVariants'
export const LIST_VARIANTS = 'listVariants'
export const SCROLL_VARIANTS = 'scrollVariants'
export const SELECT_VARIANTS = 'selectVariants'
export const STACK_VARIANTS = 'stackVariants'
export const TEXT_VARIANTS = 'textVariants'
export const TEXTAREA_VARIANTS = 'textareaVariants'

export type BOX_VARIANTS = typeof BOX_VARIANTS
export type BUTTON_VARIANTS = typeof BUTTON_VARIANTS
export type GRID_VARIANTS = typeof GRID_VARIANTS
export type IMAGE_VARIANTS = typeof IMAGE_VARIANTS
export type INPUT_VARIANTS = typeof INPUT_VARIANTS
export type LABEL_VARIANTS = typeof LABEL_VARIANTS
export type LINK_VARIANTS = typeof LINK_VARIANTS
export type LIST_VARIANTS = typeof LIST_VARIANTS
export type SCROLL_VARIANTS = typeof SCROLL_VARIANTS
export type SELECT_VARIANTS = typeof SELECT_VARIANTS
export type STACK_VARIANTS = typeof STACK_VARIANTS
export type TEXT_VARIANTS = typeof TEXT_VARIANTS
export type TEXTAREA_VARIANTS = typeof TEXTAREA_VARIANTS
