export const enum Scale {
  COLORS = 'colors',
  OPACITIES = 'opacities',
  TRANSITIONS = 'transitions',
  ANIMATIONS = 'animations',
  DURATIONS = 'durations',
  TIMINGS = 'timings',
  SPACE = 'space',
  FONTS = 'fonts',
  BORERS = 'borders',
  SIZES = 'sizes',
  FONT_SIZES = 'fontSizes',
  FONT_WEIGHTS = 'fontWeights',
  LINE_HEIGHTS = 'lineHeights',
  LETTER_SPACINGS = 'letterSpacings',
  RADII = 'radii',
  BORDERS = 'borders',
  BORDER_WIDTHS = 'borderWidths',
  BORDER_STYLES = 'borderStyles',
  SHADOWS = 'shadows',
  Z_INDICES = 'zIndices',
}

const SCALES = {
  color: Scale.COLORS,
  backgroundColor: Scale.COLORS,
  borderColor: Scale.COLORS,
  caretColor: Scale.COLORS,
  columnRuleColor: Scale.COLORS,
  opacity: Scale.OPACITIES,
  transition: Scale.TRANSITIONS,
  transitionDuration: Scale.DURATIONS,
  transitionTimingFunction: Scale.TIMINGS,
  animation: Scale.ANIMATIONS,
  animationDuration: Scale.DURATIONS,
  animationTimingFunction: Scale.TIMINGS,
  margin: Scale.SPACE,
  marginTop: Scale.SPACE,
  marginRight: Scale.SPACE,
  marginBottom: Scale.SPACE,
  marginLeft: Scale.SPACE,
  marginX: Scale.SPACE,
  marginY: Scale.SPACE,
  marginBlock: Scale.SPACE,
  marginBlockEnd: Scale.SPACE,
  marginBlockStart: Scale.SPACE,
  marginInline: Scale.SPACE,
  marginInlineEnd: Scale.SPACE,
  marginInlineStart: Scale.SPACE,
  padding: Scale.SPACE,
  paddingTop: Scale.SPACE,
  paddingRight: Scale.SPACE,
  paddingBottom: Scale.SPACE,
  paddingLeft: Scale.SPACE,
  paddingX: Scale.SPACE,
  paddingY: Scale.SPACE,
  paddingBlock: Scale.SPACE,
  paddingBlockEnd: Scale.SPACE,
  paddingBlockStart: Scale.SPACE,
  paddingInline: Scale.SPACE,
  paddingInlineEnd: Scale.SPACE,
  paddingInlineStart: Scale.SPACE,
  scrollPadding: Scale.SPACE,
  scrollPaddingTop: Scale.SPACE,
  scrollPaddingRight: Scale.SPACE,
  scrollPaddingBottom: Scale.SPACE,
  scrollPaddingLeft: Scale.SPACE,
  scrollMargin: Scale.SPACE,
  scrollMarginTop: Scale.SPACE,
  scrollMarginRight: Scale.SPACE,
  scrollMarginBottom: Scale.SPACE,
  scrollMarginLeft: Scale.SPACE,
  inset: Scale.SPACE,
  insetBlock: Scale.SPACE,
  insetBlockEnd: Scale.SPACE,
  insetBlockStart: Scale.SPACE,
  insetInline: Scale.SPACE,
  insetInlineEnd: Scale.SPACE,
  insetInlineStart: Scale.SPACE,
  top: Scale.SPACE,
  right: Scale.SPACE,
  bottom: Scale.SPACE,
  left: Scale.SPACE,
  gridGap: Scale.SPACE,
  gridColumnGap: Scale.SPACE,
  gridRowGap: Scale.SPACE,
  gap: Scale.SPACE,
  columnGap: Scale.SPACE,
  rowGap: Scale.SPACE,
  fontFamily: Scale.FONTS,
  fontSize: Scale.FONT_SIZES,
  fontWeight: Scale.FONT_WEIGHTS,
  lineHeight: Scale.LINE_HEIGHTS,
  letterSpacing: Scale.LETTER_SPACINGS,
  border: Scale.BORDERS,
  borderTop: Scale.BORDERS,
  borderRight: Scale.BORDERS,
  borderBottom: Scale.BORDERS,
  borderLeft: Scale.BORDERS,
  borderWidth: Scale.BORDER_WIDTHS,
  borderStyle: Scale.BORDER_STYLES,
  borderRadius: Scale.RADII,
  borderTopRightRadius: Scale.RADII,
  borderTopLeftRadius: Scale.RADII,
  borderBottomRightRadius: Scale.RADII,
  borderBottomLeftRadius: Scale.RADII,
  borderTopWidth: Scale.BORDER_WIDTHS,
  borderTopColor: Scale.COLORS,
  borderTopStyle: Scale.BORDER_STYLES,
  borderBottomWidth: Scale.BORDER_WIDTHS,
  borderBottomColor: Scale.COLORS,
  borderBottomStyle: Scale.BORDER_STYLES,
  borderLeftWidth: Scale.BORDER_WIDTHS,
  borderLeftColor: Scale.COLORS,
  borderLeftStyle: Scale.BORDER_STYLES,
  borderRightWidth: Scale.BORDER_WIDTHS,
  borderRightColor: Scale.COLORS,
  borderRightStyle: Scale.BORDER_STYLES,
  borderBlock: Scale.BORDERS,
  borderBlockEnd: Scale.BORDERS,
  borderBlockEndStyle: Scale.BORDER_STYLES,
  borderBlockEndWidth: Scale.BORDER_WIDTHS,
  borderBlockStart: Scale.BORDERS,
  borderBlockStartStyle: Scale.BORDER_STYLES,
  borderBlockStartWidth: Scale.BORDER_WIDTHS,
  borderBlockStyle: Scale.BORDER_STYLES,
  borderBlockWidth: Scale.BORDER_WIDTHS,
  borderEndEndRadius: Scale.RADII,
  borderEndStartRadius: Scale.RADII,
  borderInline: Scale.BORDERS,
  borderInlineEnd: Scale.BORDERS,
  borderInlineEndStyle: Scale.BORDER_STYLES,
  borderInlineEndWidth: Scale.BORDER_WIDTHS,
  borderInlineStart: Scale.BORDERS,
  borderInlineStartStyle: Scale.BORDER_STYLES,
  borderInlineStartWidth: Scale.BORDER_WIDTHS,
  borderInlineStyle: Scale.BORDER_STYLES,
  borderInlineWidth: Scale.BORDER_WIDTHS,
  borderStartEndRadius: Scale.RADII,
  borderStartStartRadius: Scale.RADII,
  outlineColor: Scale.COLORS,
  boxShadow: Scale.SHADOWS,
  textShadow: Scale.SHADOWS,
  zIndex: Scale.Z_INDICES,
  width: Scale.SIZES,
  minWidth: Scale.SIZES,
  maxWidth: Scale.SIZES,
  height: Scale.SIZES,
  minHeight: Scale.SIZES,
  maxHeight: Scale.SIZES,
  flexBasis: Scale.SIZES,
  size: Scale.SIZES,
  blockSize: Scale.SIZES,
  inlineSize: Scale.SIZES,
  maxBlockSize: Scale.SIZES,
  maxInlineSize: Scale.SIZES,
  minBlockSize: Scale.SIZES,
  minInlineSize: Scale.SIZES,
} as const

type SCALES = typeof SCALES

export default SCALES
