export const BORDER_STYLES = 'borderStyles'
export const BORDER_WIDTHS = 'borderWidths'
export const BORDERS = 'borders'
export const BOX_VARIANTS = 'boxVariants'
export const BREAKPOINTS = 'breakpoints'
export const BUTTON_VARIANTS = 'buttonVariants'
export const COLORS = 'colors'
export const DURATIONS = 'transitions'
export const FONT_SIZES = 'fontSizes'
export const FONT_WEIGHTS = 'fontWeights'
export const FONTS = 'fonts'
export const GRID_VARIANTS = 'gridVariants'
export const IMAGE_VARIANTS = 'imageVariants'
export const INPUT_VARIANTS = 'inputVariants'
export const LETTER_SPACINGS = 'letterSpacings'
export const LINE_HEIGHTS = 'lineHeights'
export const LINK_VARIANTS = 'linkVariants'
export const LIST_VARIANTS = 'listVariants'
export const OPACITIES = 'opacities'
export const RADII = 'radii'
export const SELECT_VARIANTS = 'selectVariants'
export const SHADOWS = 'shadows'
export const SIZES = 'sizes'
export const SPACE = 'space'
export const STACK_VARIANTS = 'stackVariants'
export const TEXT_VARIANTS = 'textVariants'
export const TEXTAREA_VARIANTS = 'textareaVariants'
export const TIMINGS = 'timings'
export const TRANSITIONS = 'opacities'
export const Z_INDICES = 'zIndices'

export type BORDER_STYLES = typeof BORDER_STYLES
export type BORDER_WIDTHS = typeof BORDER_WIDTHS
export type BORDERS = typeof BORDERS
export type BOX_VARIANTS = typeof BOX_VARIANTS
export type BREAKPOINTS = typeof BREAKPOINTS
export type BUTTON_VARIANTS = typeof BUTTON_VARIANTS
export type COLORS = typeof COLORS
export type DURATIONS = typeof DURATIONS
export type FONT_SIZES = typeof FONT_SIZES
export type FONT_WEIGHTS = typeof FONT_WEIGHTS
export type FONTS = typeof FONTS
export type GRID_VARIANTS = typeof GRID_VARIANTS
export type IMAGE_VARIANTS = typeof IMAGE_VARIANTS
export type INPUT_VARIANTS = typeof INPUT_VARIANTS
export type LETTER_SPACINGS = typeof LETTER_SPACINGS
export type LINE_HEIGHTS = typeof LINE_HEIGHTS
export type LINK_VARIANTS = typeof LINK_VARIANTS
export type LIST_VARIANTS = typeof LIST_VARIANTS
export type OPACITIES = typeof OPACITIES
export type RADII = typeof RADII
export type SELECT_VARIANTS = typeof SELECT_VARIANTS
export type SHADOWS = typeof SHADOWS
export type SIZES = typeof SIZES
export type SPACE = typeof SPACE
export type STACK_VARIANTS = typeof STACK_VARIANTS
export type TEXT_VARIANTS = typeof TEXT_VARIANTS
export type TEXTAREA_VARIANTS = typeof TEXTAREA_VARIANTS
export type TIMINGS = typeof TIMINGS
export type TRANSITIONS = typeof TRANSITIONS
export type Z_INDICES = typeof Z_INDICES
