import * as ThemeKey from './theme-key'

export const THEME = {
  [ThemeKey.BORDER_STYLES]: {},
  [ThemeKey.BORDER_WIDTHS]: {},
  [ThemeKey.BORDERS]: {},
  [ThemeKey.BOX_VARIANTS]: {},
  [ThemeKey.BREAKPOINTS]: { $: null },
  [ThemeKey.BUTTON_VARIANTS]: {},
  [ThemeKey.COLORS]: {},
  [ThemeKey.DURATIONS]: {},
  [ThemeKey.FONT_SIZES]: {},
  [ThemeKey.FONT_WEIGHTS]: {},
  [ThemeKey.FONTS]: {},
  [ThemeKey.GRID_VARIANTS]: {},
  [ThemeKey.IMAGE_VARIANTS]: {},
  [ThemeKey.INPUT_VARIANTS]: {},
  [ThemeKey.LETTER_SPACINGS]: {},
  [ThemeKey.LINE_HEIGHTS]: {},
  [ThemeKey.LINK_VARIANTS]: {},
  [ThemeKey.LIST_VARIANTS]: {},
  [ThemeKey.OPACITIES]: {},
  [ThemeKey.RADII]: {},
  [ThemeKey.SELECT_VARIANTS]: {},
  [ThemeKey.SHADOWS]: {},
  [ThemeKey.SIZES]: {},
  [ThemeKey.SPACE]: {},
  [ThemeKey.TEXT_VARIANTS]: {},
  [ThemeKey.TEXTAREA_VARIANTS]: {},
  [ThemeKey.TIMINGS]: {},
  [ThemeKey.TRANSITIONS]: {},
  [ThemeKey.Z_INDICES]: {},
} as const
